global:
  resolve_timeout: 5m

route:
  receiver: 'agent-integration'
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 5m
  group_by: ['alertname', 'instance', 'service']

receivers:
- name: 'agent-integration'
  webhook_configs:
  - url: 'http://host.docker.internal:5002/event'
    send_resolved: true
    http_config:
      follow_redirects: true