global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'services'
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'user-service:5000'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):\d+'
        target_label: 'service'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'user-service-node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['user-service:9100']
        labels:
          service: 'user-service'
          instance: 'container-metrics'

  - job_name: 'user-service-process-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['user-service:9256']
        labels:
          service: 'user-service'
          instance: 'process-metrics'